settings:
  enablePrePostScripts: true

minimumReleaseAgeExclude:
  - '@squarecloud/api'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar

allowBuilds:
  '@biomejs/biome': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
